//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace everisIT.AUDS.Service.Application.Utils.Resources
{
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MailData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailData() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("everisIT.SGGC.Expiration.Service.Application.Resources.MailData", typeof(MailData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The shared group.
        /// </summary>
        internal static string BodyDelete1 {
            get {
                return ResourceManager.GetString("BodyDelete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a has been deleted.
        ///Thanks you very much.
        ///Regards
        ///The system automatically generated this mail. Please do not answer..
        /// </summary>
        internal static string BodyDelete2 {
            get {
                return ResourceManager.GetString("BodyDelete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you want to renew the shared group.
        /// </summary>
        internal static string BodyExpiration1 {
            get {
                return ResourceManager.GetString("BodyExpiration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , access the link. If you do not do it, you will be disabled in.
        /// </summary>
        internal static string BodyExpiration2 {
            get {
                return ResourceManager.GetString("BodyExpiration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  days.
        ///The objective of this action is to efficiently manage the useful life of the groupes, so that they are only active while the project or area to which they belong require it.
        ///   Group name: .
        /// </summary>
        internal static string BodyExpiration3 {
            get {
                return ResourceManager.GetString("BodyExpiration3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expiration date:.
        /// </summary>
        internal static string BodyExpiration4 {
            get {
                return ResourceManager.GetString("BodyExpiration4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Group Administrator:.
        /// </summary>
        internal static string BodyExpiration5 {
            get {
                return ResourceManager.GetString("BodyExpiration5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renew shared group .
        /// </summary>
        internal static string BodyExpiration6 {
            get {
                return ResourceManager.GetString("BodyExpiration6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thank you very much
        ///Regards
        ///The system generated this email automatically. Please do not answer.
        /// </summary>
        internal static string BodyExpiration7 {
            get {
                return ResourceManager.GetString("BodyExpiration7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4.
        /// </summary>
        internal static string QuarantineStatus {
            get {
                return ResourceManager.GetString("QuarantineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The shared group.
        /// </summary>
        internal static string SubjectDelete1 {
            get {
                return ResourceManager.GetString("SubjectDelete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a deleted.
        /// </summary>
        internal static string SubjectDelete2 {
            get {
                return ResourceManager.GetString("SubjectDelete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expiration of the shared group.
        /// </summary>
        internal static string SubjectExpiration {
            get {
                return ResourceManager.GetString("SubjectExpiration", resourceCulture);
            }
        }
    }
}
